/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as RegistrosOficialesRouteImport } from './routes/registros-oficiales'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AsignaturasRouteImport } from './routes/asignaturas'
import { Route as AdministracionRouteRouteImport } from './routes/administracion/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracionIndexRouteImport } from './routes/administracion/index'
import { Route as PlanesListaRouteImport } from './routes/planes/_lista'
import { Route as AdministracionUsuariosRouteImport } from './routes/administracion/usuarios'
import { Route as AdministracionObservabilidadRouteImport } from './routes/administracion/observabilidad'
import { Route as AdministracionFlujosEstadosRouteImport } from './routes/administracion/flujos-estados'
import { Route as AdministracionFacultadesRouteImport } from './routes/administracion/facultades'
import { Route as AdministracionReferenciasRouteRouteImport } from './routes/administracion/referencias/route'
import { Route as AdministracionReferenciasIndexRouteImport } from './routes/administracion/referencias/index'
import { Route as AdministracionEstructurasIndexRouteImport } from './routes/administracion/estructuras/index'
import { Route as PlanesListaNuevoRouteImport } from './routes/planes/_lista/nuevo'
import { Route as PlanesPlanIdDetalleRouteImport } from './routes/planes/$planId/_detalle'
import { Route as AdministracionReferenciasRecientesRouteImport } from './routes/administracion/referencias/recientes'
import { Route as AdministracionReferenciasArchivosRouteImport } from './routes/administracion/referencias/archivos'
import { Route as PlanesPlanIdDetalleIndexRouteImport } from './routes/planes/$planId/_detalle/index'
import { Route as PlanesPlanIdDetalleRegistroOficialRouteImport } from './routes/planes/$planId/_detalle/registro-oficial'
import { Route as PlanesPlanIdDetalleMapaRouteImport } from './routes/planes/$planId/_detalle/mapa'
import { Route as PlanesPlanIdDetalleIaplanRouteImport } from './routes/planes/$planId/_detalle/iaplan'
import { Route as PlanesPlanIdDetalleHistorialRouteImport } from './routes/planes/$planId/_detalle/historial'
import { Route as PlanesPlanIdDetalleFlujoRouteImport } from './routes/planes/$planId/_detalle/flujo'
import { Route as PlanesPlanIdDetalleDocumentoRouteImport } from './routes/planes/$planId/_detalle/documento'
import { Route as PlanesPlanIdDetalleBloquesRouteImport } from './routes/planes/$planId/_detalle/bloques'
import { Route as PlanesPlanIdDetalleAsignaturasRouteImport } from './routes/planes/$planId/_detalle/asignaturas'
import { Route as AdministracionReferenciasRepositoriosChar123RepoIdChar125RouteImport } from './routes/administracion/referencias/repositorios/{-$repoId}'
import { Route as AdministracionFacultadesTipoNuevoRouteImport } from './routes/administracion/facultades/$tipo/nuevo'
import { Route as AdministracionEstructurasModoChar123IdChar125RouteImport } from './routes/administracion/estructuras/$modo/{-$id}'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdRouteRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/route'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdIndexRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/index'
import { Route as AdministracionEstructurasModoChar123IdChar125IndexRouteImport } from './routes/administracion/estructuras/$modo/{-$id}/index'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdRevisionRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/revision'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdResponsablesRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/responsables'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/iaasignatura'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdHistorialRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/historial'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/evaluacion'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdDocumentoRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/documento'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdContenidoRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/contenido'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/bibliografia'
import { Route as PlanesPlanIdDetalleIaplanChatRouteImport } from './routes/planes/$planId/_detalle/iaplan_.chat'
import { Route as PlanesPlanIdDetalleAsignaturasNuevaRouteImport } from './routes/planes/$planId/_detalle/asignaturas/nueva'
import { Route as AdministracionFacultadesTipoEntityIdEditarRouteImport } from './routes/administracion/facultades/$tipo/$entityId/editar'
import { Route as AdministracionFacultadesTipoEntityIdArchivarRouteImport } from './routes/administracion/facultades/$tipo/$entityId/archivar'
import { Route as AdministracionEstructurasModoChar123IdChar125PlantillasRouteImport } from './routes/administracion/estructuras/$modo/{-$id}/plantillas'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/bibliografia/index'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/iaasignatura_.chat'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosOficialesRoute = RegistrosOficialesRouteImport.update({
  id: '/registros-oficiales',
  path: '/registros-oficiales',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AsignaturasRoute = AsignaturasRouteImport.update({
  id: '/asignaturas',
  path: '/asignaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRouteRoute = AdministracionRouteRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionIndexRoute = AdministracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministracionRouteRoute,
} as any)
const PlanesListaRoute = PlanesListaRouteImport.update({
  id: '/planes/_lista',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionUsuariosRoute = AdministracionUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdministracionRouteRoute,
} as any)
const AdministracionObservabilidadRoute =
  AdministracionObservabilidadRouteImport.update({
    id: '/observabilidad',
    path: '/observabilidad',
    getParentRoute: () => AdministracionRouteRoute,
  } as any)
const AdministracionFlujosEstadosRoute =
  AdministracionFlujosEstadosRouteImport.update({
    id: '/flujos-estados',
    path: '/flujos-estados',
    getParentRoute: () => AdministracionRouteRoute,
  } as any)
const AdministracionFacultadesRoute =
  AdministracionFacultadesRouteImport.update({
    id: '/facultades',
    path: '/facultades',
    getParentRoute: () => AdministracionRouteRoute,
  } as any)
const AdministracionReferenciasRouteRoute =
  AdministracionReferenciasRouteRouteImport.update({
    id: '/referencias',
    path: '/referencias',
    getParentRoute: () => AdministracionRouteRoute,
  } as any)
const AdministracionReferenciasIndexRoute =
  AdministracionReferenciasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdministracionReferenciasRouteRoute,
  } as any)
const AdministracionEstructurasIndexRoute =
  AdministracionEstructurasIndexRouteImport.update({
    id: '/estructuras/',
    path: '/estructuras/',
    getParentRoute: () => AdministracionRouteRoute,
  } as any)
const PlanesListaNuevoRoute = PlanesListaNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => PlanesListaRoute,
} as any)
const PlanesPlanIdDetalleRoute = PlanesPlanIdDetalleRouteImport.update({
  id: '/planes/$planId/_detalle',
  path: '/planes/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionReferenciasRecientesRoute =
  AdministracionReferenciasRecientesRouteImport.update({
    id: '/recientes',
    path: '/recientes',
    getParentRoute: () => AdministracionReferenciasRouteRoute,
  } as any)
const AdministracionReferenciasArchivosRoute =
  AdministracionReferenciasArchivosRouteImport.update({
    id: '/archivos',
    path: '/archivos',
    getParentRoute: () => AdministracionReferenciasRouteRoute,
  } as any)
const PlanesPlanIdDetalleIndexRoute =
  PlanesPlanIdDetalleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const PlanesPlanIdDetalleRegistroOficialRoute =
  PlanesPlanIdDetalleRegistroOficialRouteImport.update({
    id: '/registro-oficial',
    path: '/registro-oficial',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const PlanesPlanIdDetalleMapaRoute = PlanesPlanIdDetalleMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => PlanesPlanIdDetalleRoute,
} as any)
const PlanesPlanIdDetalleIaplanRoute =
  PlanesPlanIdDetalleIaplanRouteImport.update({
    id: '/iaplan',
    path: '/iaplan',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const PlanesPlanIdDetalleHistorialRoute =
  PlanesPlanIdDetalleHistorialRouteImport.update({
    id: '/historial',
    path: '/historial',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const PlanesPlanIdDetalleFlujoRoute =
  PlanesPlanIdDetalleFlujoRouteImport.update({
    id: '/flujo',
    path: '/flujo',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const PlanesPlanIdDetalleDocumentoRoute =
  PlanesPlanIdDetalleDocumentoRouteImport.update({
    id: '/documento',
    path: '/documento',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const PlanesPlanIdDetalleBloquesRoute =
  PlanesPlanIdDetalleBloquesRouteImport.update({
    id: '/bloques',
    path: '/bloques',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const PlanesPlanIdDetalleAsignaturasRoute =
  PlanesPlanIdDetalleAsignaturasRouteImport.update({
    id: '/asignaturas',
    path: '/asignaturas',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const AdministracionReferenciasRepositoriosChar123RepoIdChar125Route =
  AdministracionReferenciasRepositoriosChar123RepoIdChar125RouteImport.update({
    id: '/repositorios/{-$repoId}',
    path: '/repositorios/{-$repoId}',
    getParentRoute: () => AdministracionReferenciasRouteRoute,
  } as any)
const AdministracionFacultadesTipoNuevoRoute =
  AdministracionFacultadesTipoNuevoRouteImport.update({
    id: '/$tipo/nuevo',
    path: '/$tipo/nuevo',
    getParentRoute: () => AdministracionFacultadesRoute,
  } as any)
const AdministracionEstructurasModoChar123IdChar125Route =
  AdministracionEstructurasModoChar123IdChar125RouteImport.update({
    id: '/estructuras/$modo/{-$id}',
    path: '/estructuras/$modo/{-$id}',
    getParentRoute: () => AdministracionRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdRouteRoute =
  PlanesPlanIdAsignaturasAsignaturaIdRouteRouteImport.update({
    id: '/planes/$planId/asignaturas/$asignaturaId',
    path: '/planes/$planId/asignaturas/$asignaturaId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdIndexRoute =
  PlanesPlanIdAsignaturasAsignaturaIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const AdministracionEstructurasModoChar123IdChar125IndexRoute =
  AdministracionEstructurasModoChar123IdChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdministracionEstructurasModoChar123IdChar125Route,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdRevisionRoute =
  PlanesPlanIdAsignaturasAsignaturaIdRevisionRouteImport.update({
    id: '/revision',
    path: '/revision',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdResponsablesRoute =
  PlanesPlanIdAsignaturasAsignaturaIdResponsablesRouteImport.update({
    id: '/responsables',
    path: '/responsables',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRoute =
  PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRouteImport.update({
    id: '/iaasignatura',
    path: '/iaasignatura',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdHistorialRoute =
  PlanesPlanIdAsignaturasAsignaturaIdHistorialRouteImport.update({
    id: '/historial',
    path: '/historial',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRoute =
  PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRouteImport.update({
    id: '/evaluacion',
    path: '/evaluacion',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdDocumentoRoute =
  PlanesPlanIdAsignaturasAsignaturaIdDocumentoRouteImport.update({
    id: '/documento',
    path: '/documento',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdContenidoRoute =
  PlanesPlanIdAsignaturasAsignaturaIdContenidoRouteImport.update({
    id: '/contenido',
    path: '/contenido',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRoute =
  PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteImport.update({
    id: '/bibliografia',
    path: '/bibliografia',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdDetalleIaplanChatRoute =
  PlanesPlanIdDetalleIaplanChatRouteImport.update({
    id: '/iaplan_/chat',
    path: '/iaplan/chat',
    getParentRoute: () => PlanesPlanIdDetalleRoute,
  } as any)
const PlanesPlanIdDetalleAsignaturasNuevaRoute =
  PlanesPlanIdDetalleAsignaturasNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => PlanesPlanIdDetalleAsignaturasRoute,
  } as any)
const AdministracionFacultadesTipoEntityIdEditarRoute =
  AdministracionFacultadesTipoEntityIdEditarRouteImport.update({
    id: '/$tipo/$entityId/editar',
    path: '/$tipo/$entityId/editar',
    getParentRoute: () => AdministracionFacultadesRoute,
  } as any)
const AdministracionFacultadesTipoEntityIdArchivarRoute =
  AdministracionFacultadesTipoEntityIdArchivarRouteImport.update({
    id: '/$tipo/$entityId/archivar',
    path: '/$tipo/$entityId/archivar',
    getParentRoute: () => AdministracionFacultadesRoute,
  } as any)
const AdministracionEstructurasModoChar123IdChar125PlantillasRoute =
  AdministracionEstructurasModoChar123IdChar125PlantillasRouteImport.update({
    id: '/plantillas',
    path: '/plantillas',
    getParentRoute: () => AdministracionEstructurasModoChar123IdChar125Route,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRoute =
  PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRoute =
  PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRouteImport.update({
    id: '/iaasignatura_/chat',
    path: '/iaasignatura/chat',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRoute =
  PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRouteRouteWithChildren
  '/asignaturas': typeof AsignaturasRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registros-oficiales': typeof RegistrosOficialesRoute
  '/update-password': typeof UpdatePasswordRoute
  '/administracion/referencias': typeof AdministracionReferenciasRouteRouteWithChildren
  '/administracion/facultades': typeof AdministracionFacultadesRouteWithChildren
  '/administracion/flujos-estados': typeof AdministracionFlujosEstadosRoute
  '/administracion/observabilidad': typeof AdministracionObservabilidadRoute
  '/administracion/usuarios': typeof AdministracionUsuariosRoute
  '/planes': typeof PlanesListaRouteWithChildren
  '/administracion/': typeof AdministracionIndexRoute
  '/administracion/referencias/archivos': typeof AdministracionReferenciasArchivosRoute
  '/administracion/referencias/recientes': typeof AdministracionReferenciasRecientesRoute
  '/planes/$planId': typeof PlanesPlanIdDetalleRouteWithChildren
  '/planes/nuevo': typeof PlanesListaNuevoRoute
  '/administracion/estructuras/': typeof AdministracionEstructurasIndexRoute
  '/administracion/referencias/': typeof AdministracionReferenciasIndexRoute
  '/planes/$planId/asignaturas/$asignaturaId': typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRouteWithChildren
  '/administracion/estructuras/$modo/{-$id}': typeof AdministracionEstructurasModoChar123IdChar125RouteWithChildren
  '/administracion/facultades/$tipo/nuevo': typeof AdministracionFacultadesTipoNuevoRoute
  '/administracion/referencias/repositorios/{-$repoId}': typeof AdministracionReferenciasRepositoriosChar123RepoIdChar125Route
  '/planes/$planId/asignaturas': typeof PlanesPlanIdDetalleAsignaturasRouteWithChildren
  '/planes/$planId/bloques': typeof PlanesPlanIdDetalleBloquesRoute
  '/planes/$planId/documento': typeof PlanesPlanIdDetalleDocumentoRoute
  '/planes/$planId/flujo': typeof PlanesPlanIdDetalleFlujoRoute
  '/planes/$planId/historial': typeof PlanesPlanIdDetalleHistorialRoute
  '/planes/$planId/iaplan': typeof PlanesPlanIdDetalleIaplanRoute
  '/planes/$planId/mapa': typeof PlanesPlanIdDetalleMapaRoute
  '/planes/$planId/registro-oficial': typeof PlanesPlanIdDetalleRegistroOficialRoute
  '/planes/$planId/': typeof PlanesPlanIdDetalleIndexRoute
  '/administracion/estructuras/$modo/{-$id}/plantillas': typeof AdministracionEstructurasModoChar123IdChar125PlantillasRoute
  '/administracion/facultades/$tipo/$entityId/archivar': typeof AdministracionFacultadesTipoEntityIdArchivarRoute
  '/administracion/facultades/$tipo/$entityId/editar': typeof AdministracionFacultadesTipoEntityIdEditarRoute
  '/planes/$planId/asignaturas/nueva': typeof PlanesPlanIdDetalleAsignaturasNuevaRoute
  '/planes/$planId/iaplan/chat': typeof PlanesPlanIdDetalleIaplanChatRoute
  '/planes/$planId/asignaturas/$asignaturaId/bibliografia': typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteWithChildren
  '/planes/$planId/asignaturas/$asignaturaId/contenido': typeof PlanesPlanIdAsignaturasAsignaturaIdContenidoRoute
  '/planes/$planId/asignaturas/$asignaturaId/documento': typeof PlanesPlanIdAsignaturasAsignaturaIdDocumentoRoute
  '/planes/$planId/asignaturas/$asignaturaId/evaluacion': typeof PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRoute
  '/planes/$planId/asignaturas/$asignaturaId/historial': typeof PlanesPlanIdAsignaturasAsignaturaIdHistorialRoute
  '/planes/$planId/asignaturas/$asignaturaId/iaasignatura': typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRoute
  '/planes/$planId/asignaturas/$asignaturaId/responsables': typeof PlanesPlanIdAsignaturasAsignaturaIdResponsablesRoute
  '/planes/$planId/asignaturas/$asignaturaId/revision': typeof PlanesPlanIdAsignaturasAsignaturaIdRevisionRoute
  '/administracion/estructuras/$modo/{-$id}/': typeof AdministracionEstructurasModoChar123IdChar125IndexRoute
  '/planes/$planId/asignaturas/$asignaturaId/': typeof PlanesPlanIdAsignaturasAsignaturaIdIndexRoute
  '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva': typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRoute
  '/planes/$planId/asignaturas/$asignaturaId/iaasignatura/chat': typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRoute
  '/planes/$planId/asignaturas/$asignaturaId/bibliografia/': typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asignaturas': typeof AsignaturasRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registros-oficiales': typeof RegistrosOficialesRoute
  '/update-password': typeof UpdatePasswordRoute
  '/administracion/facultades': typeof AdministracionFacultadesRouteWithChildren
  '/administracion/flujos-estados': typeof AdministracionFlujosEstadosRoute
  '/administracion/observabilidad': typeof AdministracionObservabilidadRoute
  '/administracion/usuarios': typeof AdministracionUsuariosRoute
  '/planes': typeof PlanesListaRouteWithChildren
  '/administracion': typeof AdministracionIndexRoute
  '/administracion/referencias/archivos': typeof AdministracionReferenciasArchivosRoute
  '/administracion/referencias/recientes': typeof AdministracionReferenciasRecientesRoute
  '/planes/nuevo': typeof PlanesListaNuevoRoute
  '/administracion/estructuras': typeof AdministracionEstructurasIndexRoute
  '/administracion/referencias': typeof AdministracionReferenciasIndexRoute
  '/administracion/facultades/$tipo/nuevo': typeof AdministracionFacultadesTipoNuevoRoute
  '/administracion/referencias/repositorios/{-$repoId}': typeof AdministracionReferenciasRepositoriosChar123RepoIdChar125Route
  '/planes/$planId/asignaturas': typeof PlanesPlanIdDetalleAsignaturasRouteWithChildren
  '/planes/$planId/bloques': typeof PlanesPlanIdDetalleBloquesRoute
  '/planes/$planId/documento': typeof PlanesPlanIdDetalleDocumentoRoute
  '/planes/$planId/flujo': typeof PlanesPlanIdDetalleFlujoRoute
  '/planes/$planId/historial': typeof PlanesPlanIdDetalleHistorialRoute
  '/planes/$planId/iaplan': typeof PlanesPlanIdDetalleIaplanRoute
  '/planes/$planId/mapa': typeof PlanesPlanIdDetalleMapaRoute
  '/planes/$planId/registro-oficial': typeof PlanesPlanIdDetalleRegistroOficialRoute
  '/planes/$planId': typeof PlanesPlanIdDetalleIndexRoute
  '/administracion/estructuras/$modo/{-$id}/plantillas': typeof AdministracionEstructurasModoChar123IdChar125PlantillasRoute
  '/administracion/facultades/$tipo/$entityId/archivar': typeof AdministracionFacultadesTipoEntityIdArchivarRoute
  '/administracion/facultades/$tipo/$entityId/editar': typeof AdministracionFacultadesTipoEntityIdEditarRoute
  '/planes/$planId/asignaturas/nueva': typeof PlanesPlanIdDetalleAsignaturasNuevaRoute
  '/planes/$planId/iaplan/chat': typeof PlanesPlanIdDetalleIaplanChatRoute
  '/planes/$planId/asignaturas/$asignaturaId/contenido': typeof PlanesPlanIdAsignaturasAsignaturaIdContenidoRoute
  '/planes/$planId/asignaturas/$asignaturaId/documento': typeof PlanesPlanIdAsignaturasAsignaturaIdDocumentoRoute
  '/planes/$planId/asignaturas/$asignaturaId/evaluacion': typeof PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRoute
  '/planes/$planId/asignaturas/$asignaturaId/historial': typeof PlanesPlanIdAsignaturasAsignaturaIdHistorialRoute
  '/planes/$planId/asignaturas/$asignaturaId/iaasignatura': typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRoute
  '/planes/$planId/asignaturas/$asignaturaId/responsables': typeof PlanesPlanIdAsignaturasAsignaturaIdResponsablesRoute
  '/planes/$planId/asignaturas/$asignaturaId/revision': typeof PlanesPlanIdAsignaturasAsignaturaIdRevisionRoute
  '/administracion/estructuras/$modo/{-$id}': typeof AdministracionEstructurasModoChar123IdChar125IndexRoute
  '/planes/$planId/asignaturas/$asignaturaId': typeof PlanesPlanIdAsignaturasAsignaturaIdIndexRoute
  '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva': typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRoute
  '/planes/$planId/asignaturas/$asignaturaId/iaasignatura/chat': typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRoute
  '/planes/$planId/asignaturas/$asignaturaId/bibliografia': typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracion': typeof AdministracionRouteRouteWithChildren
  '/asignaturas': typeof AsignaturasRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registros-oficiales': typeof RegistrosOficialesRoute
  '/update-password': typeof UpdatePasswordRoute
  '/administracion/referencias': typeof AdministracionReferenciasRouteRouteWithChildren
  '/administracion/facultades': typeof AdministracionFacultadesRouteWithChildren
  '/administracion/flujos-estados': typeof AdministracionFlujosEstadosRoute
  '/administracion/observabilidad': typeof AdministracionObservabilidadRoute
  '/administracion/usuarios': typeof AdministracionUsuariosRoute
  '/planes/_lista': typeof PlanesListaRouteWithChildren
  '/administracion/': typeof AdministracionIndexRoute
  '/administracion/referencias/archivos': typeof AdministracionReferenciasArchivosRoute
  '/administracion/referencias/recientes': typeof AdministracionReferenciasRecientesRoute
  '/planes/$planId/_detalle': typeof PlanesPlanIdDetalleRouteWithChildren
  '/planes/_lista/nuevo': typeof PlanesListaNuevoRoute
  '/administracion/estructuras/': typeof AdministracionEstructurasIndexRoute
  '/administracion/referencias/': typeof AdministracionReferenciasIndexRoute
  '/planes/$planId/asignaturas/$asignaturaId': typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRouteWithChildren
  '/administracion/estructuras/$modo/{-$id}': typeof AdministracionEstructurasModoChar123IdChar125RouteWithChildren
  '/administracion/facultades/$tipo/nuevo': typeof AdministracionFacultadesTipoNuevoRoute
  '/administracion/referencias/repositorios/{-$repoId}': typeof AdministracionReferenciasRepositoriosChar123RepoIdChar125Route
  '/planes/$planId/_detalle/asignaturas': typeof PlanesPlanIdDetalleAsignaturasRouteWithChildren
  '/planes/$planId/_detalle/bloques': typeof PlanesPlanIdDetalleBloquesRoute
  '/planes/$planId/_detalle/documento': typeof PlanesPlanIdDetalleDocumentoRoute
  '/planes/$planId/_detalle/flujo': typeof PlanesPlanIdDetalleFlujoRoute
  '/planes/$planId/_detalle/historial': typeof PlanesPlanIdDetalleHistorialRoute
  '/planes/$planId/_detalle/iaplan': typeof PlanesPlanIdDetalleIaplanRoute
  '/planes/$planId/_detalle/mapa': typeof PlanesPlanIdDetalleMapaRoute
  '/planes/$planId/_detalle/registro-oficial': typeof PlanesPlanIdDetalleRegistroOficialRoute
  '/planes/$planId/_detalle/': typeof PlanesPlanIdDetalleIndexRoute
  '/administracion/estructuras/$modo/{-$id}/plantillas': typeof AdministracionEstructurasModoChar123IdChar125PlantillasRoute
  '/administracion/facultades/$tipo/$entityId/archivar': typeof AdministracionFacultadesTipoEntityIdArchivarRoute
  '/administracion/facultades/$tipo/$entityId/editar': typeof AdministracionFacultadesTipoEntityIdEditarRoute
  '/planes/$planId/_detalle/asignaturas/nueva': typeof PlanesPlanIdDetalleAsignaturasNuevaRoute
  '/planes/$planId/_detalle/iaplan_/chat': typeof PlanesPlanIdDetalleIaplanChatRoute
  '/planes/$planId/asignaturas/$asignaturaId/bibliografia': typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteWithChildren
  '/planes/$planId/asignaturas/$asignaturaId/contenido': typeof PlanesPlanIdAsignaturasAsignaturaIdContenidoRoute
  '/planes/$planId/asignaturas/$asignaturaId/documento': typeof PlanesPlanIdAsignaturasAsignaturaIdDocumentoRoute
  '/planes/$planId/asignaturas/$asignaturaId/evaluacion': typeof PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRoute
  '/planes/$planId/asignaturas/$asignaturaId/historial': typeof PlanesPlanIdAsignaturasAsignaturaIdHistorialRoute
  '/planes/$planId/asignaturas/$asignaturaId/iaasignatura': typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRoute
  '/planes/$planId/asignaturas/$asignaturaId/responsables': typeof PlanesPlanIdAsignaturasAsignaturaIdResponsablesRoute
  '/planes/$planId/asignaturas/$asignaturaId/revision': typeof PlanesPlanIdAsignaturasAsignaturaIdRevisionRoute
  '/administracion/estructuras/$modo/{-$id}/': typeof AdministracionEstructurasModoChar123IdChar125IndexRoute
  '/planes/$planId/asignaturas/$asignaturaId/': typeof PlanesPlanIdAsignaturasAsignaturaIdIndexRoute
  '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva': typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRoute
  '/planes/$planId/asignaturas/$asignaturaId/iaasignatura_/chat': typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRoute
  '/planes/$planId/asignaturas/$asignaturaId/bibliografia/': typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/asignaturas'
    | '/login'
    | '/registro'
    | '/registros-oficiales'
    | '/update-password'
    | '/administracion/referencias'
    | '/administracion/facultades'
    | '/administracion/flujos-estados'
    | '/administracion/observabilidad'
    | '/administracion/usuarios'
    | '/planes'
    | '/administracion/'
    | '/administracion/referencias/archivos'
    | '/administracion/referencias/recientes'
    | '/planes/$planId'
    | '/planes/nuevo'
    | '/administracion/estructuras/'
    | '/administracion/referencias/'
    | '/planes/$planId/asignaturas/$asignaturaId'
    | '/administracion/estructuras/$modo/{-$id}'
    | '/administracion/facultades/$tipo/nuevo'
    | '/administracion/referencias/repositorios/{-$repoId}'
    | '/planes/$planId/asignaturas'
    | '/planes/$planId/bloques'
    | '/planes/$planId/documento'
    | '/planes/$planId/flujo'
    | '/planes/$planId/historial'
    | '/planes/$planId/iaplan'
    | '/planes/$planId/mapa'
    | '/planes/$planId/registro-oficial'
    | '/planes/$planId/'
    | '/administracion/estructuras/$modo/{-$id}/plantillas'
    | '/administracion/facultades/$tipo/$entityId/archivar'
    | '/administracion/facultades/$tipo/$entityId/editar'
    | '/planes/$planId/asignaturas/nueva'
    | '/planes/$planId/iaplan/chat'
    | '/planes/$planId/asignaturas/$asignaturaId/bibliografia'
    | '/planes/$planId/asignaturas/$asignaturaId/contenido'
    | '/planes/$planId/asignaturas/$asignaturaId/documento'
    | '/planes/$planId/asignaturas/$asignaturaId/evaluacion'
    | '/planes/$planId/asignaturas/$asignaturaId/historial'
    | '/planes/$planId/asignaturas/$asignaturaId/iaasignatura'
    | '/planes/$planId/asignaturas/$asignaturaId/responsables'
    | '/planes/$planId/asignaturas/$asignaturaId/revision'
    | '/administracion/estructuras/$modo/{-$id}/'
    | '/planes/$planId/asignaturas/$asignaturaId/'
    | '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva'
    | '/planes/$planId/asignaturas/$asignaturaId/iaasignatura/chat'
    | '/planes/$planId/asignaturas/$asignaturaId/bibliografia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asignaturas'
    | '/login'
    | '/registro'
    | '/registros-oficiales'
    | '/update-password'
    | '/administracion/facultades'
    | '/administracion/flujos-estados'
    | '/administracion/observabilidad'
    | '/administracion/usuarios'
    | '/planes'
    | '/administracion'
    | '/administracion/referencias/archivos'
    | '/administracion/referencias/recientes'
    | '/planes/nuevo'
    | '/administracion/estructuras'
    | '/administracion/referencias'
    | '/administracion/facultades/$tipo/nuevo'
    | '/administracion/referencias/repositorios/{-$repoId}'
    | '/planes/$planId/asignaturas'
    | '/planes/$planId/bloques'
    | '/planes/$planId/documento'
    | '/planes/$planId/flujo'
    | '/planes/$planId/historial'
    | '/planes/$planId/iaplan'
    | '/planes/$planId/mapa'
    | '/planes/$planId/registro-oficial'
    | '/planes/$planId'
    | '/administracion/estructuras/$modo/{-$id}/plantillas'
    | '/administracion/facultades/$tipo/$entityId/archivar'
    | '/administracion/facultades/$tipo/$entityId/editar'
    | '/planes/$planId/asignaturas/nueva'
    | '/planes/$planId/iaplan/chat'
    | '/planes/$planId/asignaturas/$asignaturaId/contenido'
    | '/planes/$planId/asignaturas/$asignaturaId/documento'
    | '/planes/$planId/asignaturas/$asignaturaId/evaluacion'
    | '/planes/$planId/asignaturas/$asignaturaId/historial'
    | '/planes/$planId/asignaturas/$asignaturaId/iaasignatura'
    | '/planes/$planId/asignaturas/$asignaturaId/responsables'
    | '/planes/$planId/asignaturas/$asignaturaId/revision'
    | '/administracion/estructuras/$modo/{-$id}'
    | '/planes/$planId/asignaturas/$asignaturaId'
    | '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva'
    | '/planes/$planId/asignaturas/$asignaturaId/iaasignatura/chat'
    | '/planes/$planId/asignaturas/$asignaturaId/bibliografia'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/asignaturas'
    | '/login'
    | '/registro'
    | '/registros-oficiales'
    | '/update-password'
    | '/administracion/referencias'
    | '/administracion/facultades'
    | '/administracion/flujos-estados'
    | '/administracion/observabilidad'
    | '/administracion/usuarios'
    | '/planes/_lista'
    | '/administracion/'
    | '/administracion/referencias/archivos'
    | '/administracion/referencias/recientes'
    | '/planes/$planId/_detalle'
    | '/planes/_lista/nuevo'
    | '/administracion/estructuras/'
    | '/administracion/referencias/'
    | '/planes/$planId/asignaturas/$asignaturaId'
    | '/administracion/estructuras/$modo/{-$id}'
    | '/administracion/facultades/$tipo/nuevo'
    | '/administracion/referencias/repositorios/{-$repoId}'
    | '/planes/$planId/_detalle/asignaturas'
    | '/planes/$planId/_detalle/bloques'
    | '/planes/$planId/_detalle/documento'
    | '/planes/$planId/_detalle/flujo'
    | '/planes/$planId/_detalle/historial'
    | '/planes/$planId/_detalle/iaplan'
    | '/planes/$planId/_detalle/mapa'
    | '/planes/$planId/_detalle/registro-oficial'
    | '/planes/$planId/_detalle/'
    | '/administracion/estructuras/$modo/{-$id}/plantillas'
    | '/administracion/facultades/$tipo/$entityId/archivar'
    | '/administracion/facultades/$tipo/$entityId/editar'
    | '/planes/$planId/_detalle/asignaturas/nueva'
    | '/planes/$planId/_detalle/iaplan_/chat'
    | '/planes/$planId/asignaturas/$asignaturaId/bibliografia'
    | '/planes/$planId/asignaturas/$asignaturaId/contenido'
    | '/planes/$planId/asignaturas/$asignaturaId/documento'
    | '/planes/$planId/asignaturas/$asignaturaId/evaluacion'
    | '/planes/$planId/asignaturas/$asignaturaId/historial'
    | '/planes/$planId/asignaturas/$asignaturaId/iaasignatura'
    | '/planes/$planId/asignaturas/$asignaturaId/responsables'
    | '/planes/$planId/asignaturas/$asignaturaId/revision'
    | '/administracion/estructuras/$modo/{-$id}/'
    | '/planes/$planId/asignaturas/$asignaturaId/'
    | '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva'
    | '/planes/$planId/asignaturas/$asignaturaId/iaasignatura_/chat'
    | '/planes/$planId/asignaturas/$asignaturaId/bibliografia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracionRouteRoute: typeof AdministracionRouteRouteWithChildren
  AsignaturasRoute: typeof AsignaturasRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  RegistrosOficialesRoute: typeof RegistrosOficialesRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  PlanesListaRoute: typeof PlanesListaRouteWithChildren
  PlanesPlanIdDetalleRoute: typeof PlanesPlanIdDetalleRouteWithChildren
  PlanesPlanIdAsignaturasAsignaturaIdRouteRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros-oficiales': {
      id: '/registros-oficiales'
      path: '/registros-oficiales'
      fullPath: '/registros-oficiales'
      preLoaderRoute: typeof RegistrosOficialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asignaturas': {
      id: '/asignaturas'
      path: '/asignaturas'
      fullPath: '/asignaturas'
      preLoaderRoute: typeof AsignaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/': {
      id: '/administracion/'
      path: '/'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AdministracionIndexRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/planes/_lista': {
      id: '/planes/_lista'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/usuarios': {
      id: '/administracion/usuarios'
      path: '/usuarios'
      fullPath: '/administracion/usuarios'
      preLoaderRoute: typeof AdministracionUsuariosRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/observabilidad': {
      id: '/administracion/observabilidad'
      path: '/observabilidad'
      fullPath: '/administracion/observabilidad'
      preLoaderRoute: typeof AdministracionObservabilidadRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/flujos-estados': {
      id: '/administracion/flujos-estados'
      path: '/flujos-estados'
      fullPath: '/administracion/flujos-estados'
      preLoaderRoute: typeof AdministracionFlujosEstadosRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/facultades': {
      id: '/administracion/facultades'
      path: '/facultades'
      fullPath: '/administracion/facultades'
      preLoaderRoute: typeof AdministracionFacultadesRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/referencias': {
      id: '/administracion/referencias'
      path: '/referencias'
      fullPath: '/administracion/referencias'
      preLoaderRoute: typeof AdministracionReferenciasRouteRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/administracion/referencias/': {
      id: '/administracion/referencias/'
      path: '/'
      fullPath: '/administracion/referencias/'
      preLoaderRoute: typeof AdministracionReferenciasIndexRouteImport
      parentRoute: typeof AdministracionReferenciasRouteRoute
    }
    '/administracion/estructuras/': {
      id: '/administracion/estructuras/'
      path: '/estructuras'
      fullPath: '/administracion/estructuras/'
      preLoaderRoute: typeof AdministracionEstructurasIndexRouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/planes/_lista/nuevo': {
      id: '/planes/_lista/nuevo'
      path: '/nuevo'
      fullPath: '/planes/nuevo'
      preLoaderRoute: typeof PlanesListaNuevoRouteImport
      parentRoute: typeof PlanesListaRoute
    }
    '/planes/$planId/_detalle': {
      id: '/planes/$planId/_detalle'
      path: '/planes/$planId'
      fullPath: '/planes/$planId'
      preLoaderRoute: typeof PlanesPlanIdDetalleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion/referencias/recientes': {
      id: '/administracion/referencias/recientes'
      path: '/recientes'
      fullPath: '/administracion/referencias/recientes'
      preLoaderRoute: typeof AdministracionReferenciasRecientesRouteImport
      parentRoute: typeof AdministracionReferenciasRouteRoute
    }
    '/administracion/referencias/archivos': {
      id: '/administracion/referencias/archivos'
      path: '/archivos'
      fullPath: '/administracion/referencias/archivos'
      preLoaderRoute: typeof AdministracionReferenciasArchivosRouteImport
      parentRoute: typeof AdministracionReferenciasRouteRoute
    }
    '/planes/$planId/_detalle/': {
      id: '/planes/$planId/_detalle/'
      path: '/'
      fullPath: '/planes/$planId/'
      preLoaderRoute: typeof PlanesPlanIdDetalleIndexRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/registro-oficial': {
      id: '/planes/$planId/_detalle/registro-oficial'
      path: '/registro-oficial'
      fullPath: '/planes/$planId/registro-oficial'
      preLoaderRoute: typeof PlanesPlanIdDetalleRegistroOficialRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/mapa': {
      id: '/planes/$planId/_detalle/mapa'
      path: '/mapa'
      fullPath: '/planes/$planId/mapa'
      preLoaderRoute: typeof PlanesPlanIdDetalleMapaRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/iaplan': {
      id: '/planes/$planId/_detalle/iaplan'
      path: '/iaplan'
      fullPath: '/planes/$planId/iaplan'
      preLoaderRoute: typeof PlanesPlanIdDetalleIaplanRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/historial': {
      id: '/planes/$planId/_detalle/historial'
      path: '/historial'
      fullPath: '/planes/$planId/historial'
      preLoaderRoute: typeof PlanesPlanIdDetalleHistorialRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/flujo': {
      id: '/planes/$planId/_detalle/flujo'
      path: '/flujo'
      fullPath: '/planes/$planId/flujo'
      preLoaderRoute: typeof PlanesPlanIdDetalleFlujoRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/documento': {
      id: '/planes/$planId/_detalle/documento'
      path: '/documento'
      fullPath: '/planes/$planId/documento'
      preLoaderRoute: typeof PlanesPlanIdDetalleDocumentoRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/bloques': {
      id: '/planes/$planId/_detalle/bloques'
      path: '/bloques'
      fullPath: '/planes/$planId/bloques'
      preLoaderRoute: typeof PlanesPlanIdDetalleBloquesRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/asignaturas': {
      id: '/planes/$planId/_detalle/asignaturas'
      path: '/asignaturas'
      fullPath: '/planes/$planId/asignaturas'
      preLoaderRoute: typeof PlanesPlanIdDetalleAsignaturasRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/administracion/referencias/repositorios/{-$repoId}': {
      id: '/administracion/referencias/repositorios/{-$repoId}'
      path: '/repositorios/{-$repoId}'
      fullPath: '/administracion/referencias/repositorios/{-$repoId}'
      preLoaderRoute: typeof AdministracionReferenciasRepositoriosChar123RepoIdChar125RouteImport
      parentRoute: typeof AdministracionReferenciasRouteRoute
    }
    '/administracion/facultades/$tipo/nuevo': {
      id: '/administracion/facultades/$tipo/nuevo'
      path: '/$tipo/nuevo'
      fullPath: '/administracion/facultades/$tipo/nuevo'
      preLoaderRoute: typeof AdministracionFacultadesTipoNuevoRouteImport
      parentRoute: typeof AdministracionFacultadesRoute
    }
    '/administracion/estructuras/$modo/{-$id}': {
      id: '/administracion/estructuras/$modo/{-$id}'
      path: '/estructuras/$modo/{-$id}'
      fullPath: '/administracion/estructuras/$modo/{-$id}'
      preLoaderRoute: typeof AdministracionEstructurasModoChar123IdChar125RouteImport
      parentRoute: typeof AdministracionRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId': {
      id: '/planes/$planId/asignaturas/$asignaturaId'
      path: '/planes/$planId/asignaturas/$asignaturaId'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes/$planId/asignaturas/$asignaturaId/': {
      id: '/planes/$planId/asignaturas/$asignaturaId/'
      path: '/'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdIndexRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/administracion/estructuras/$modo/{-$id}/': {
      id: '/administracion/estructuras/$modo/{-$id}/'
      path: '/'
      fullPath: '/administracion/estructuras/$modo/{-$id}/'
      preLoaderRoute: typeof AdministracionEstructurasModoChar123IdChar125IndexRouteImport
      parentRoute: typeof AdministracionEstructurasModoChar123IdChar125Route
    }
    '/planes/$planId/asignaturas/$asignaturaId/revision': {
      id: '/planes/$planId/asignaturas/$asignaturaId/revision'
      path: '/revision'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/revision'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRevisionRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/responsables': {
      id: '/planes/$planId/asignaturas/$asignaturaId/responsables'
      path: '/responsables'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/responsables'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdResponsablesRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/iaasignatura': {
      id: '/planes/$planId/asignaturas/$asignaturaId/iaasignatura'
      path: '/iaasignatura'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/iaasignatura'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/historial': {
      id: '/planes/$planId/asignaturas/$asignaturaId/historial'
      path: '/historial'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/historial'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdHistorialRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/evaluacion': {
      id: '/planes/$planId/asignaturas/$asignaturaId/evaluacion'
      path: '/evaluacion'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/evaluacion'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/documento': {
      id: '/planes/$planId/asignaturas/$asignaturaId/documento'
      path: '/documento'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/documento'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdDocumentoRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/contenido': {
      id: '/planes/$planId/asignaturas/$asignaturaId/contenido'
      path: '/contenido'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/contenido'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdContenidoRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/bibliografia': {
      id: '/planes/$planId/asignaturas/$asignaturaId/bibliografia'
      path: '/bibliografia'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/bibliografia'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/_detalle/iaplan_/chat': {
      id: '/planes/$planId/_detalle/iaplan_/chat'
      path: '/iaplan/chat'
      fullPath: '/planes/$planId/iaplan/chat'
      preLoaderRoute: typeof PlanesPlanIdDetalleIaplanChatRouteImport
      parentRoute: typeof PlanesPlanIdDetalleRoute
    }
    '/planes/$planId/_detalle/asignaturas/nueva': {
      id: '/planes/$planId/_detalle/asignaturas/nueva'
      path: '/nueva'
      fullPath: '/planes/$planId/asignaturas/nueva'
      preLoaderRoute: typeof PlanesPlanIdDetalleAsignaturasNuevaRouteImport
      parentRoute: typeof PlanesPlanIdDetalleAsignaturasRoute
    }
    '/administracion/facultades/$tipo/$entityId/editar': {
      id: '/administracion/facultades/$tipo/$entityId/editar'
      path: '/$tipo/$entityId/editar'
      fullPath: '/administracion/facultades/$tipo/$entityId/editar'
      preLoaderRoute: typeof AdministracionFacultadesTipoEntityIdEditarRouteImport
      parentRoute: typeof AdministracionFacultadesRoute
    }
    '/administracion/facultades/$tipo/$entityId/archivar': {
      id: '/administracion/facultades/$tipo/$entityId/archivar'
      path: '/$tipo/$entityId/archivar'
      fullPath: '/administracion/facultades/$tipo/$entityId/archivar'
      preLoaderRoute: typeof AdministracionFacultadesTipoEntityIdArchivarRouteImport
      parentRoute: typeof AdministracionFacultadesRoute
    }
    '/administracion/estructuras/$modo/{-$id}/plantillas': {
      id: '/administracion/estructuras/$modo/{-$id}/plantillas'
      path: '/plantillas'
      fullPath: '/administracion/estructuras/$modo/{-$id}/plantillas'
      preLoaderRoute: typeof AdministracionEstructurasModoChar123IdChar125PlantillasRouteImport
      parentRoute: typeof AdministracionEstructurasModoChar123IdChar125Route
    }
    '/planes/$planId/asignaturas/$asignaturaId/bibliografia/': {
      id: '/planes/$planId/asignaturas/$asignaturaId/bibliografia/'
      path: '/'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/bibliografia/'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/iaasignatura_/chat': {
      id: '/planes/$planId/asignaturas/$asignaturaId/iaasignatura_/chat'
      path: '/iaasignatura/chat'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/iaasignatura/chat'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
    }
    '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva': {
      id: '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva'
      path: '/nueva'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId/bibliografia/nueva'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRoute
    }
  }
}

interface AdministracionReferenciasRouteRouteChildren {
  AdministracionReferenciasArchivosRoute: typeof AdministracionReferenciasArchivosRoute
  AdministracionReferenciasRecientesRoute: typeof AdministracionReferenciasRecientesRoute
  AdministracionReferenciasIndexRoute: typeof AdministracionReferenciasIndexRoute
  AdministracionReferenciasRepositoriosChar123RepoIdChar125Route: typeof AdministracionReferenciasRepositoriosChar123RepoIdChar125Route
}

const AdministracionReferenciasRouteRouteChildren: AdministracionReferenciasRouteRouteChildren =
  {
    AdministracionReferenciasArchivosRoute:
      AdministracionReferenciasArchivosRoute,
    AdministracionReferenciasRecientesRoute:
      AdministracionReferenciasRecientesRoute,
    AdministracionReferenciasIndexRoute: AdministracionReferenciasIndexRoute,
    AdministracionReferenciasRepositoriosChar123RepoIdChar125Route:
      AdministracionReferenciasRepositoriosChar123RepoIdChar125Route,
  }

const AdministracionReferenciasRouteRouteWithChildren =
  AdministracionReferenciasRouteRoute._addFileChildren(
    AdministracionReferenciasRouteRouteChildren,
  )

interface AdministracionFacultadesRouteChildren {
  AdministracionFacultadesTipoNuevoRoute: typeof AdministracionFacultadesTipoNuevoRoute
  AdministracionFacultadesTipoEntityIdArchivarRoute: typeof AdministracionFacultadesTipoEntityIdArchivarRoute
  AdministracionFacultadesTipoEntityIdEditarRoute: typeof AdministracionFacultadesTipoEntityIdEditarRoute
}

const AdministracionFacultadesRouteChildren: AdministracionFacultadesRouteChildren =
  {
    AdministracionFacultadesTipoNuevoRoute:
      AdministracionFacultadesTipoNuevoRoute,
    AdministracionFacultadesTipoEntityIdArchivarRoute:
      AdministracionFacultadesTipoEntityIdArchivarRoute,
    AdministracionFacultadesTipoEntityIdEditarRoute:
      AdministracionFacultadesTipoEntityIdEditarRoute,
  }

const AdministracionFacultadesRouteWithChildren =
  AdministracionFacultadesRoute._addFileChildren(
    AdministracionFacultadesRouteChildren,
  )

interface AdministracionEstructurasModoChar123IdChar125RouteChildren {
  AdministracionEstructurasModoChar123IdChar125PlantillasRoute: typeof AdministracionEstructurasModoChar123IdChar125PlantillasRoute
  AdministracionEstructurasModoChar123IdChar125IndexRoute: typeof AdministracionEstructurasModoChar123IdChar125IndexRoute
}

const AdministracionEstructurasModoChar123IdChar125RouteChildren: AdministracionEstructurasModoChar123IdChar125RouteChildren =
  {
    AdministracionEstructurasModoChar123IdChar125PlantillasRoute:
      AdministracionEstructurasModoChar123IdChar125PlantillasRoute,
    AdministracionEstructurasModoChar123IdChar125IndexRoute:
      AdministracionEstructurasModoChar123IdChar125IndexRoute,
  }

const AdministracionEstructurasModoChar123IdChar125RouteWithChildren =
  AdministracionEstructurasModoChar123IdChar125Route._addFileChildren(
    AdministracionEstructurasModoChar123IdChar125RouteChildren,
  )

interface AdministracionRouteRouteChildren {
  AdministracionReferenciasRouteRoute: typeof AdministracionReferenciasRouteRouteWithChildren
  AdministracionFacultadesRoute: typeof AdministracionFacultadesRouteWithChildren
  AdministracionFlujosEstadosRoute: typeof AdministracionFlujosEstadosRoute
  AdministracionObservabilidadRoute: typeof AdministracionObservabilidadRoute
  AdministracionUsuariosRoute: typeof AdministracionUsuariosRoute
  AdministracionIndexRoute: typeof AdministracionIndexRoute
  AdministracionEstructurasIndexRoute: typeof AdministracionEstructurasIndexRoute
  AdministracionEstructurasModoChar123IdChar125Route: typeof AdministracionEstructurasModoChar123IdChar125RouteWithChildren
}

const AdministracionRouteRouteChildren: AdministracionRouteRouteChildren = {
  AdministracionReferenciasRouteRoute:
    AdministracionReferenciasRouteRouteWithChildren,
  AdministracionFacultadesRoute: AdministracionFacultadesRouteWithChildren,
  AdministracionFlujosEstadosRoute: AdministracionFlujosEstadosRoute,
  AdministracionObservabilidadRoute: AdministracionObservabilidadRoute,
  AdministracionUsuariosRoute: AdministracionUsuariosRoute,
  AdministracionIndexRoute: AdministracionIndexRoute,
  AdministracionEstructurasIndexRoute: AdministracionEstructurasIndexRoute,
  AdministracionEstructurasModoChar123IdChar125Route:
    AdministracionEstructurasModoChar123IdChar125RouteWithChildren,
}

const AdministracionRouteRouteWithChildren =
  AdministracionRouteRoute._addFileChildren(AdministracionRouteRouteChildren)

interface PlanesListaRouteChildren {
  PlanesListaNuevoRoute: typeof PlanesListaNuevoRoute
}

const PlanesListaRouteChildren: PlanesListaRouteChildren = {
  PlanesListaNuevoRoute: PlanesListaNuevoRoute,
}

const PlanesListaRouteWithChildren = PlanesListaRoute._addFileChildren(
  PlanesListaRouteChildren,
)

interface PlanesPlanIdDetalleAsignaturasRouteChildren {
  PlanesPlanIdDetalleAsignaturasNuevaRoute: typeof PlanesPlanIdDetalleAsignaturasNuevaRoute
}

const PlanesPlanIdDetalleAsignaturasRouteChildren: PlanesPlanIdDetalleAsignaturasRouteChildren =
  {
    PlanesPlanIdDetalleAsignaturasNuevaRoute:
      PlanesPlanIdDetalleAsignaturasNuevaRoute,
  }

const PlanesPlanIdDetalleAsignaturasRouteWithChildren =
  PlanesPlanIdDetalleAsignaturasRoute._addFileChildren(
    PlanesPlanIdDetalleAsignaturasRouteChildren,
  )

interface PlanesPlanIdDetalleRouteChildren {
  PlanesPlanIdDetalleAsignaturasRoute: typeof PlanesPlanIdDetalleAsignaturasRouteWithChildren
  PlanesPlanIdDetalleBloquesRoute: typeof PlanesPlanIdDetalleBloquesRoute
  PlanesPlanIdDetalleDocumentoRoute: typeof PlanesPlanIdDetalleDocumentoRoute
  PlanesPlanIdDetalleFlujoRoute: typeof PlanesPlanIdDetalleFlujoRoute
  PlanesPlanIdDetalleHistorialRoute: typeof PlanesPlanIdDetalleHistorialRoute
  PlanesPlanIdDetalleIaplanRoute: typeof PlanesPlanIdDetalleIaplanRoute
  PlanesPlanIdDetalleMapaRoute: typeof PlanesPlanIdDetalleMapaRoute
  PlanesPlanIdDetalleRegistroOficialRoute: typeof PlanesPlanIdDetalleRegistroOficialRoute
  PlanesPlanIdDetalleIndexRoute: typeof PlanesPlanIdDetalleIndexRoute
  PlanesPlanIdDetalleIaplanChatRoute: typeof PlanesPlanIdDetalleIaplanChatRoute
}

const PlanesPlanIdDetalleRouteChildren: PlanesPlanIdDetalleRouteChildren = {
  PlanesPlanIdDetalleAsignaturasRoute:
    PlanesPlanIdDetalleAsignaturasRouteWithChildren,
  PlanesPlanIdDetalleBloquesRoute: PlanesPlanIdDetalleBloquesRoute,
  PlanesPlanIdDetalleDocumentoRoute: PlanesPlanIdDetalleDocumentoRoute,
  PlanesPlanIdDetalleFlujoRoute: PlanesPlanIdDetalleFlujoRoute,
  PlanesPlanIdDetalleHistorialRoute: PlanesPlanIdDetalleHistorialRoute,
  PlanesPlanIdDetalleIaplanRoute: PlanesPlanIdDetalleIaplanRoute,
  PlanesPlanIdDetalleMapaRoute: PlanesPlanIdDetalleMapaRoute,
  PlanesPlanIdDetalleRegistroOficialRoute:
    PlanesPlanIdDetalleRegistroOficialRoute,
  PlanesPlanIdDetalleIndexRoute: PlanesPlanIdDetalleIndexRoute,
  PlanesPlanIdDetalleIaplanChatRoute: PlanesPlanIdDetalleIaplanChatRoute,
}

const PlanesPlanIdDetalleRouteWithChildren =
  PlanesPlanIdDetalleRoute._addFileChildren(PlanesPlanIdDetalleRouteChildren)

interface PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteChildren {
  PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRoute
  PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRoute
}

const PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteChildren: PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteChildren =
  {
    PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRoute:
      PlanesPlanIdAsignaturasAsignaturaIdBibliografiaNuevaRoute,
    PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRoute:
      PlanesPlanIdAsignaturasAsignaturaIdBibliografiaIndexRoute,
  }

const PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteWithChildren =
  PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRoute._addFileChildren(
    PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteChildren,
  )

interface PlanesPlanIdAsignaturasAsignaturaIdRouteRouteChildren {
  PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteWithChildren
  PlanesPlanIdAsignaturasAsignaturaIdContenidoRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdContenidoRoute
  PlanesPlanIdAsignaturasAsignaturaIdDocumentoRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdDocumentoRoute
  PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRoute
  PlanesPlanIdAsignaturasAsignaturaIdHistorialRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdHistorialRoute
  PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRoute
  PlanesPlanIdAsignaturasAsignaturaIdResponsablesRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdResponsablesRoute
  PlanesPlanIdAsignaturasAsignaturaIdRevisionRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRevisionRoute
  PlanesPlanIdAsignaturasAsignaturaIdIndexRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdIndexRoute
  PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRoute
}

const PlanesPlanIdAsignaturasAsignaturaIdRouteRouteChildren: PlanesPlanIdAsignaturasAsignaturaIdRouteRouteChildren =
  {
    PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRoute:
      PlanesPlanIdAsignaturasAsignaturaIdBibliografiaRouteWithChildren,
    PlanesPlanIdAsignaturasAsignaturaIdContenidoRoute:
      PlanesPlanIdAsignaturasAsignaturaIdContenidoRoute,
    PlanesPlanIdAsignaturasAsignaturaIdDocumentoRoute:
      PlanesPlanIdAsignaturasAsignaturaIdDocumentoRoute,
    PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRoute:
      PlanesPlanIdAsignaturasAsignaturaIdEvaluacionRoute,
    PlanesPlanIdAsignaturasAsignaturaIdHistorialRoute:
      PlanesPlanIdAsignaturasAsignaturaIdHistorialRoute,
    PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRoute:
      PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaRoute,
    PlanesPlanIdAsignaturasAsignaturaIdResponsablesRoute:
      PlanesPlanIdAsignaturasAsignaturaIdResponsablesRoute,
    PlanesPlanIdAsignaturasAsignaturaIdRevisionRoute:
      PlanesPlanIdAsignaturasAsignaturaIdRevisionRoute,
    PlanesPlanIdAsignaturasAsignaturaIdIndexRoute:
      PlanesPlanIdAsignaturasAsignaturaIdIndexRoute,
    PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRoute:
      PlanesPlanIdAsignaturasAsignaturaIdIaasignaturaChatRoute,
  }

const PlanesPlanIdAsignaturasAsignaturaIdRouteRouteWithChildren =
  PlanesPlanIdAsignaturasAsignaturaIdRouteRoute._addFileChildren(
    PlanesPlanIdAsignaturasAsignaturaIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracionRouteRoute: AdministracionRouteRouteWithChildren,
  AsignaturasRoute: AsignaturasRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  RegistrosOficialesRoute: RegistrosOficialesRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  PlanesListaRoute: PlanesListaRouteWithChildren,
  PlanesPlanIdDetalleRoute: PlanesPlanIdDetalleRouteWithChildren,
  PlanesPlanIdAsignaturasAsignaturaIdRouteRoute:
    PlanesPlanIdAsignaturasAsignaturaIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
