/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as PlanesListaRouteRouteImport } from './routes/planes/_lista/route'
import { Route as PlanesPlanIdIndexRouteImport } from './routes/planes/$planId/index'
import { Route as PlanesListaNuevoRouteImport } from './routes/planes/_lista/nuevo'
import { Route as PlanesPlanIdAsignaturasListaRouteRouteImport } from './routes/planes/$planId/asignaturas/_lista/route'
import { Route as PlanesPlanIdAsignaturasAsignaturaIdRouteRouteImport } from './routes/planes/$planId/asignaturas/$asignaturaId/route'
import { Route as PlanesPlanIdAsignaturasListaNuevaRouteImport } from './routes/planes/$planId/asignaturas/_lista/nueva'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesListaRouteRoute = PlanesListaRouteRouteImport.update({
  id: '/planes/_lista',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesPlanIdIndexRoute = PlanesPlanIdIndexRouteImport.update({
  id: '/planes/$planId/',
  path: '/planes/$planId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesListaNuevoRoute = PlanesListaNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => PlanesListaRouteRoute,
} as any)
const PlanesPlanIdAsignaturasListaRouteRoute =
  PlanesPlanIdAsignaturasListaRouteRouteImport.update({
    id: '/planes/$planId/asignaturas/_lista',
    path: '/planes/$planId/asignaturas',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlanesPlanIdAsignaturasAsignaturaIdRouteRoute =
  PlanesPlanIdAsignaturasAsignaturaIdRouteRouteImport.update({
    id: '/planes/$planId/asignaturas/$asignaturaId',
    path: '/planes/$planId/asignaturas/$asignaturaId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlanesPlanIdAsignaturasListaNuevaRoute =
  PlanesPlanIdAsignaturasListaNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => PlanesPlanIdAsignaturasListaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planes': typeof PlanesListaRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/planes/nuevo': typeof PlanesListaNuevoRoute
  '/planes/$planId': typeof PlanesPlanIdIndexRoute
  '/planes/$planId/asignaturas/$asignaturaId': typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
  '/planes/$planId/asignaturas': typeof PlanesPlanIdAsignaturasListaRouteRouteWithChildren
  '/planes/$planId/asignaturas/nueva': typeof PlanesPlanIdAsignaturasListaNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planes': typeof PlanesListaRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/planes/nuevo': typeof PlanesListaNuevoRoute
  '/planes/$planId': typeof PlanesPlanIdIndexRoute
  '/planes/$planId/asignaturas/$asignaturaId': typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
  '/planes/$planId/asignaturas': typeof PlanesPlanIdAsignaturasListaRouteRouteWithChildren
  '/planes/$planId/asignaturas/nueva': typeof PlanesPlanIdAsignaturasListaNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/planes/_lista': typeof PlanesListaRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/planes/_lista/nuevo': typeof PlanesListaNuevoRoute
  '/planes/$planId/': typeof PlanesPlanIdIndexRoute
  '/planes/$planId/asignaturas/$asignaturaId': typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
  '/planes/$planId/asignaturas/_lista': typeof PlanesPlanIdAsignaturasListaRouteRouteWithChildren
  '/planes/$planId/asignaturas/_lista/nueva': typeof PlanesPlanIdAsignaturasListaNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/planes'
    | '/demo/tanstack-query'
    | '/planes/nuevo'
    | '/planes/$planId'
    | '/planes/$planId/asignaturas/$asignaturaId'
    | '/planes/$planId/asignaturas'
    | '/planes/$planId/asignaturas/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/planes'
    | '/demo/tanstack-query'
    | '/planes/nuevo'
    | '/planes/$planId'
    | '/planes/$planId/asignaturas/$asignaturaId'
    | '/planes/$planId/asignaturas'
    | '/planes/$planId/asignaturas/nueva'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/planes/_lista'
    | '/demo/tanstack-query'
    | '/planes/_lista/nuevo'
    | '/planes/$planId/'
    | '/planes/$planId/asignaturas/$asignaturaId'
    | '/planes/$planId/asignaturas/_lista'
    | '/planes/$planId/asignaturas/_lista/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PlanesListaRouteRoute: typeof PlanesListaRouteRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  PlanesPlanIdIndexRoute: typeof PlanesPlanIdIndexRoute
  PlanesPlanIdAsignaturasAsignaturaIdRouteRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRoute
  PlanesPlanIdAsignaturasListaRouteRoute: typeof PlanesPlanIdAsignaturasListaRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes/_lista': {
      id: '/planes/_lista'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesListaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes/$planId/': {
      id: '/planes/$planId/'
      path: '/planes/$planId'
      fullPath: '/planes/$planId'
      preLoaderRoute: typeof PlanesPlanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes/_lista/nuevo': {
      id: '/planes/_lista/nuevo'
      path: '/nuevo'
      fullPath: '/planes/nuevo'
      preLoaderRoute: typeof PlanesListaNuevoRouteImport
      parentRoute: typeof PlanesListaRouteRoute
    }
    '/planes/$planId/asignaturas/_lista': {
      id: '/planes/$planId/asignaturas/_lista'
      path: '/planes/$planId/asignaturas'
      fullPath: '/planes/$planId/asignaturas'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasListaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes/$planId/asignaturas/$asignaturaId': {
      id: '/planes/$planId/asignaturas/$asignaturaId'
      path: '/planes/$planId/asignaturas/$asignaturaId'
      fullPath: '/planes/$planId/asignaturas/$asignaturaId'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasAsignaturaIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes/$planId/asignaturas/_lista/nueva': {
      id: '/planes/$planId/asignaturas/_lista/nueva'
      path: '/nueva'
      fullPath: '/planes/$planId/asignaturas/nueva'
      preLoaderRoute: typeof PlanesPlanIdAsignaturasListaNuevaRouteImport
      parentRoute: typeof PlanesPlanIdAsignaturasListaRouteRoute
    }
  }
}

interface PlanesListaRouteRouteChildren {
  PlanesListaNuevoRoute: typeof PlanesListaNuevoRoute
}

const PlanesListaRouteRouteChildren: PlanesListaRouteRouteChildren = {
  PlanesListaNuevoRoute: PlanesListaNuevoRoute,
}

const PlanesListaRouteRouteWithChildren =
  PlanesListaRouteRoute._addFileChildren(PlanesListaRouteRouteChildren)

interface PlanesPlanIdAsignaturasListaRouteRouteChildren {
  PlanesPlanIdAsignaturasListaNuevaRoute: typeof PlanesPlanIdAsignaturasListaNuevaRoute
}

const PlanesPlanIdAsignaturasListaRouteRouteChildren: PlanesPlanIdAsignaturasListaRouteRouteChildren =
  {
    PlanesPlanIdAsignaturasListaNuevaRoute:
      PlanesPlanIdAsignaturasListaNuevaRoute,
  }

const PlanesPlanIdAsignaturasListaRouteRouteWithChildren =
  PlanesPlanIdAsignaturasListaRouteRoute._addFileChildren(
    PlanesPlanIdAsignaturasListaRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PlanesListaRouteRoute: PlanesListaRouteRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  PlanesPlanIdIndexRoute: PlanesPlanIdIndexRoute,
  PlanesPlanIdAsignaturasAsignaturaIdRouteRoute:
    PlanesPlanIdAsignaturasAsignaturaIdRouteRoute,
  PlanesPlanIdAsignaturasListaRouteRoute:
    PlanesPlanIdAsignaturasListaRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
